session8/pj/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('movie/', views.movie, name="movie"),
    path('drama/', views.drama, name="drama"),
    path('entertain/', views.entertain, name="entertain"),
    path('<int:article_id>/', views.detail, name="detail"),
    path('new/', views.new, name="new"),
]

session8/pj/pj/urls.py
from django.contrib import admin
from django.urls import include, path
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('blog/', include('blog.urls')),
]

session8/pj/blog/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length = 100)
    create_date = models.DateTimeField()

    def __str__(self):
        return self.name

class Article(models.Model):
    title = models.CharField(max_length = 100)
    content = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    create_date = models.DateTimeField()

    def __str__(self):
        return self.title

session8/pj/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.utils import timezone
from .models import Article, Category

# Create your views here.

def index(request):
    m_articles = Article.objects.filter(category = 1)
    d_articles = Article.objects.filter(category = 2)
    e_articles = Article.objects.filter(category = 3)
    m_category = Category.objects.get(id = 1)
    d_category = Category.objects.get(id = 2)
    e_category = Category.objects.get(id = 3)
    context = {
        'm_articles' : len(m_articles),
        'd_articles' : len(d_articles),
        'e_articles' : len(e_articles),
        'm_category' : m_category,
        'd_category' : d_category,
        'e_category' : e_category,
    }
    return render(request, 'blog/index.html', context)
    # return HttpResponse("메인 페이지입니다.")

def movie(request):
    m_articles = Article.objects.filter(category = 1)
    context = {
        'm_articles' : m_articles,
    }
    # return HttpResponse("영화 페이지에요.")
    return render(request, 'blog/movie.html', context)

def drama(request):
    d_articles = Article.objects.filter(category = 2)
    context = {
        'd_articles' : d_articles,
    }
    # return HttpResponse("드라마 페이지에요.")
    return render(request, 'blog/drama.html', context)

def entertain(request):
    e_articles = Article.objects.filter(category = 3)
    context = {
        'e_articles' : e_articles,
    }
    # return HttpResponse("예능 페이지에요.")
    return render(request, 'blog/entertain.html', context)


def detail(request, article_id):
    """
    기사 상세 내용 조회 페이지
    """
    an_article_for_detail = get_object_or_404(Article, pk=article_id)
    context = {'article' : an_article_for_detail}
    return render(request, 'blog/detail.html', context)

def new(request):
    """
    글 쓰기 페이지
    """
    if request.method == 'POST':
        c = 'category'
        d = Category(pk=c)
        e = d.name

        new_article = Article.objects.create(
            title = request.POST['title'],
            content = request.POST['content'],
            create_date = timezone.now(),
            category = request.POST[e],
        )
        
        
            
        return redirect('blog/detail', article_id=new_article.pk)
    else:
        return render(request, 'blog/new.html')

session8/pj/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>THE ARTICLES</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

session8/pj/templates/blog/detail.html
{% extends 'base.html' %}
{% block content %}
<body>
    <h2>상세 조회 페이지에요</h2>
    <h2>TITLE</h2>
    <h3>{{article.title}}</h3>
    <h2>CONTENT</h2>
    <h3>{{article.content}}</h3>
    <h2>TIME</h2>
    <h3>{{article.create_date}}</h3>
</body>


{% endblock %}

session8/pj/templates/blog/drama.html
{% extends 'base.html' %}
{% block content %}
<body>
    <h2>드라마 페이지에요</h2>
    {% for d_article in d_articles %}
        <li>
            <a href = "{% url 'blog:detail' d_article.id %}">{{d_article.title}}</a>
        </li>
    {% endfor %}
    <h3><a href = "{% url 'blog:new' %}">글 쓰기</a></h3>
  
</body>

{% endblock %}

session8/pj/templates/blog/entertain.html
{% extends 'base.html' %}
{% block content %}
<body>
    <h2>예능 페이지에요</h2>
    {% for e_article in e_articles %}
        <li>
            <a href = "{% url 'blog:detail' e_article.id %}">{{e_article.title}}</a>
        </li>
    {% endfor %}
    <h3><a href = "{% url 'blog:new' %}">글 쓰기</a></h3>
   
</body>

{% endblock %}

session8/pj/templates/blog/index.html
{% extends 'base.html' %}
{% block content %}
<h2>메인 게시판 페이지에요</h2>
<h2>
    <a href = "blog/movie">{{m_category}} 카테고리</a>
</h2>
<h2>글 개수</h2>
<h3>{{m_articles}}</h3>
<h2>
    <a href = "blog/drama">{{d_category}} 카테고리</a>
</h2>
<h2>글 개수</h2>
<h3>{{d_articles}}</h3>
<h2>
    <a href = "blog/entertain">{{e_category}} 카테고리</a>
</h2>
<h2>글 개수</h2>
<h3>{{e_articles}}</h3>

{% endblock %}

session8/pj/templates/blog/movie.html
{% extends 'base.html' %}
{% block content %}
<body>
    <h2>영화 페이지에요</h2>
    {% for m_article in m_articles %}
        <li>
            <a href = "{% url 'blog:detail' m_article.id %}">{{m_article.title}}</a>
        </li>
    {% endfor %}
    <h3><a href = "{% url 'blog:new' %}">글 쓰기</a></h3>
    

</body>

{% endblock %}

session8/pj/templates/blog/new.html
{% extends 'base.html' %}
{% block content %}
<body>
    <h2>글 쓰기 페이지에요</h2>
    <form method="POST">
        {% csrf_token %}
        <input name="title" placeholder="글 제목을 입력해주세요">
        <br />
        <textarea name="content" placeholder="글 내용을 입력해주세요" id="content" rows"15"></textarea>
        <br />
        <select name="category">
            <option value="">--------</option>
            <option value=0>영화</option>
            <option value=1>드라마</option>
            <option value=2>예능</option>
            </select>
        <br />
        <button type="submit">글 쓰기</button>
    </form>
</body>


{% endblock %}